version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: empreinte-db
    ports:
      - "1400:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "olfa!gaidi@123"
    volumes:
      - empreinte-db-data:/var/opt/mssql
    healthcheck:
      test: >
        ["CMD", "/opt/mssql-tools/bin/sqlcmd",
         "-U", "sa", "-P", "olfa!gaidi@123",
         "-Q", "SELECT 1"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: empreinte-backend
    ports:
      - "7281:443"
    environment:
      # Database connection settings
      DB_HOST: db
      DB_PORT: 1433
      DB_NAME: empreinte_db
      DB_USER: sa
      DB_PASSWORD: olfa!gaidi@123
      # (add any other env vars your app needs)
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  
    container_name: empreinte-frontend
    ports:
      - "3000:80"
    # if your frontend needs to call the backend via env:
    environment:
      REACT_APP_API_URL: https://empreinte-backend:443

volumes:
  empreinte-db-data:
    name: empreinte-db-data
