# Étape 1 : build React
FROM node:18 AS builder
WORKDIR /app

COPY ./EmpreintCarboneFrontend/package*.json ./
RUN npm install
COPY ./EmpreintCarboneFrontend ./
RUN npm run build

# Étape 2 : image finale NGINX
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf

# ✅ Ce chemin est correct avec ta structure actuelle
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
