# Étape de build
FROM node:18 as build
WORKDIR /app

COPY ./EmpreintCarboneFrontend/package*.json ./
RUN npm install

COPY ./EmpreintCarboneFrontend/ ./
RUN npm run build

# Étape de production
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
